language:
  - node_js
node_js:
  - '5.12'
before_install:
  - npm install -g grunt-cli bower yo generator-karma generator-angular
  - gem install compass
install:
  - npm install
  - bower install --no-interactive
script:
  - grunt package
after_success:
  if ([ "$TRAVIS_BRANCH" == "master" ] || [ ! -z "$TRAVIS_TAG" ]) && 
      [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    
    if ([ -d "dist" ] ); then
      echo "Deploying to dist repo";

      openssl aes-256-cbc -K $encrypted_42099b4af021_key -iv $encrypted_42099b4af021_iv -in deploy-web-educ-web.pem.enc -out deploy-web-educ-web.pem -d;

      eval "$(ssh-agent -s)";
      chmod 600 deploy-web-educ-web.pem;
      ssh-add deploy-web-educ-web.pem;

      if ([ ! -z "$TRAVIS_TAG" ]); then
        cd dist;
        git init;
        git remote add origin "git@github.com:cyrilchapon/demo-web-educ-web-dist.git";

        git config user.email "cyril.chapon@live.com";
        git config user.name "Travis CI";

        git add -A .;

        git tag $TRAVIS_TAG;
        git push -u origin --tags --force;
      else
        git clone git@github.com:cyrilchapon/demo-web-educ-web-dist.git olddist;
        cp -r olddist/.git dist;
        cd dist;

        git config user.email "cyril.chapon@live.com";
        git config user.name "Travis CI";

        git add -A .;

        git commit -m "New distribution";
        git push -u origin master;
      fi
    else
      echo "Skipping deploy because no dist directory found";
    fi
  else
    echo "Skipping deploy on dist repo";
  fi
