language:
  - node_js
node_js:
  - "5.8"
before_install:
  - npm install -g grunt-cli bower yo generator-karma generator-angular
  - gem install compass
install:
  - npm install
  - bower install --no-interactive
script:
  - grunt build