language:
  - node_js
node_js:
  - "5.8"
before_install:
  - npm install -g grunt-cli bower yo generator-karma generator-angular
  - gem install compass
install:
  - npm install
  - bower install --no-interactive
script:
  - grunt build
deploy:
  provider: releases
  api_key:
    secure: CV5Mr3T3VPHDrBqWDT8osXmdPblgoyDFAgWHwbu+dCy4X+2pu6YJ4wRCkAwl16JyG3P/MKgXDNy7xVhUTOTMuWrFHvU5IpJxVQylZI2yTWBhClaaydm1oEHnUZACbQANoK3G48/u3obM2SR1ZPSGKmCajAYwJV777Nxf/8KYbAJvGeaMfqWtaqyco2REBmO87ZaHYhOBq+AmsfyZxgVO3q9ltTeIASbnLPtdpUa/wZX77PMCMCQQt0tFHAlh2666yCaZjX2SQb/SAtXNL1QpVA2r5JJxgsMqjD8vEBuSWOGTZK4kHZ/0qIYzFYdFbeJ0B/IuM8c0NJtSuQtXHGchfAyGDLNtuaOL4ukVgT7oAkoZfjrUScO9dS7uh6zqHnYj10a8eyzYapEdrkhK1AwmUOB+4KbzeQ5Cv9xzIUkDMmpJGCFrslaDU7A2/2B8AXhDo0McmosPAaw2JA2e0Is3PTKGqn7Eu/32+xNuKXbJHDQU6eEk6YwKeHIvhNHiaQHeK+9xElrqfdOBHsSkMnGBnMfVJriDfGdFE0GrrFMcbNyapIvw9QHS9XcdA/FM+bxvxy3uL8bfAUtCQMSVuG/qVHkKeM3ZpyOAKgH9yL85415EbPHg+zqSW6dbMhN6bxHu6EYFyRrDhULFjCOJWlvu9VT1Ap1LThIRzGBymtmNI8A=
  file_glob: true
  file: "dist/*"
  skip_cleanup: true
  on:
    tags: true